---
title: "NGSAdmix"
author: "Ira Cooke"
output:
  pdf_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(ggpubr)
source("R/ngsadmix.R")
```

```{r}
sample_data <- read_sample_admix_data()
```

Before looking at population structure with NGSadmix we first use PCAdmix to attempt to infer the correct number of clusters. 

```{r}


covmat <- read_table2("hpc/NGSadmix/pcangst.cov",col_names = FALSE) %>% 
  as.matrix()

colnames(covmat) <- sample_data$Sample
rownames(covmat) <- sample_data$Sample

pop_eigen <- eigen(covmat)

pop_pca <- data.frame(x=pop_eigen$vectors[,1],y=pop_eigen$vectors[,2],sample_data) %>% 
  mutate(Location = str_remove(Location,"GBR - ")) %>% 
  filter(Location!="Unknown")

ggplot(pop_pca ,aes(x=x,y=y)) + geom_point(aes(shape=Location,color=Pop),size=2) + 
  theme_pubclean() +
  guides(color='none') +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank()) +
  xlab("PC1") + ylab("PC2") +
  scale_color_manual(values = c("Cluster3" = "#e41a1c","Cluster2" = "#377eb8", "Cluster1" = "#4daf4a"))

ggsave("figures/PCAngst.png")
```


It might also be of interest to zoom in on individual clusters to see if there is sub-structure

```{r}
ggplot(pop_pca ,aes(x=x,y=y)) + 
  geom_point(aes(shape=Location,color=Location),size=2) + 
  facet_wrap(~Pop,nrow = 1, scales = "free") +
  theme_pubclean() +
  guides(shape='none') +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank()) +
  xlab("PC1") + ylab("PC2") #+
#  scale_color_manual(values = c("Cluster3" = "#e41a1c","Cluster2" = "#377eb8", "Cluster1" = "#4daf4a"))

ggsave("figures/PCAngst_SeparatePops.png",width = 16)
```
